# Trigger顶级必要的配置参数
Desc = "使用Http监听端口并接收POST原始字节数据"
Name = "HttpServerTrigger"
Topic = "http/001"
RpcAddress = "0.0.0.0:5573"
Broadcast = false

# SerialPort配置参数
[SerialPortOptions]
  serialPort = "COM4"
  readTimeout = "1s"
  bufferSize = 64
  baudRate = 115200
  dataBit = 8
  parity = "N"
  stopBits = 1