# 顶级必要的配置参数
Name = "DongKongTrigger"
Topic = "dongkong/events"

# 东控主板配置参数
[BoardOptions]
  serialNumber = 123456

# SocketServer配置参数
[SocketServerOptions]
  address = [
      "udp://0.0.0.0:5570"
  ]