# 顶级必要的配置参数
Name = "SocketClientEndpoint"
RpcAddress = "0.0.0.0:5570"
Broadcast = false

# Socket客户端配置参数
[SocketClientOptions]
  targetAddress = "tcp://remote.domain:8080"
  bufferSize = 1024
  readTimeout = "1s"
  writeTimeout = "1s"
  autoReconnect = true
  reconnectInterval = "3s"
  keepAlive = true
  keepAliveInterval = "3s"