# Trigger顶级必要的配置参数
Desc = "使用Socket监听端口并接收原始字节数据"
Name = "SocketServerTrigger"
Topic = "tcp/001"
Broadcast = false
Address = [
    "tcp://0.0.0.0:5570",
    "udp://0.0.0.0:5570"
]

# SocketServer配置参数
[SocketServerOptions]
  # 服务端处理线程，默认为1，单线程
  numLoops = 1 #
  # 负载均衡，多线程时生效，取值：Random, RoundRobin, LeastConnections
  loadBalance = "random"

# Socket客户端配置参数
[SocketClientOptions]
  targetAddress = "tcp://remote.domain:8080"
  bufferSize = 1024
  readTimeout = "1s"
  writeTimeout = "1s"
  autoReconnect = true
  reconnectInterval = "3s"
  keepAlive = true
  keepAliveInterval = "3s"