# 顶级必要的配置参数
Name = "HttpClientEndpoint"
RpcAddress = "0.0.0.0:5570"
Broadcast = false

# HttpClient配置参数
[HttpClientOptions]
  targetUrl = "http://remote-server.com/post-path"
  contentType = "application/json"
  clientTimeout = "5s"