# 顶级必要的配置参数
Name = "SerialClientTrigger"
Topic = "http/001"

# SerialPort配置参数
[SerialPortOptions]
  serialPort = "/dev/ttyUSB0"
  readTimeout = "1s"
  bufferSize = 64
  baudRate = 115200
  dataBit = 8
  parity = "N"
  stopBits = 1