# 顶级必要的配置参数
Name = "SocketServerTrigger"
Topic = "socket/001"

# SocketServer配置参数
[SocketServerOptions]
  # 服务端处理线程，默认为1，单线程
  numLoops = 1 #
  # 负载均衡，多线程时生效，取值：Random, RoundRobin, LeastConnections
  loadBalance = "random"
  address = [
      "tcp://0.0.0.0:5570",
      "udp://0.0.0.0:5571"
  ]